// libs/blacklist.ts

export interface BlacklistEntry {
  name: string;
  nic?: string;
  passport?: string;
}

export const blacklistedCustomers: BlacklistEntry[] = [
  { name: "Velupillai Revathan" },
  { name: "Raman Sinnappa a.k.a Sinnappa Master" },
  { name: "Karuna Kularathnam a.k.a Nallathambi" },
  { name: "Thoraisamy Selvakumar a.k.a Raju" },
  { name: "Ramachandran Abiram a.k.a Niroshan" },
  { name: "Shanmuga sundaram Kanthasekaran a.k.a Kanthasekaran a.k.a Kandan a.k.a Thambi a.k.a Shankar" },
  { name: "Kanagarasa Ravisankar a.k.a Shangili a.k.a Ravi" },
  { name: "Kishnapillai Sivagnanam (Kitnapille) a.k.a Elavan a.k.a Ilam" },
  { name: "Selvamanikkam Arunakirithas a.k.a Ambarasu a.k.a Ranjan" },
  { name: "Jeyarathnam Jeyachandran a.k.a Chandu" },
  { name: "Patikunaraja Ramesh a.k.a Subesh Sathgunarajah" },
  { name: "Bandula Gajaweera Gunarathna" },
  { name: "Annalingam Kandeepan" },
  { name: "Kanigalayam Siri Sankar a.k.a Ilan Kadeer" },
  { name: "Subramaniam Vivekanandan a.k.a Siran" },
  { name: "Jegathewan Wakeesan a.k.a Sinnawan a.k.a Manikkam" },
  { name: "Kandavanam Shivashangaran a.k.a Arivmani a.k.a Ariv" },
  { name: "Mery Jesow Anrothy Janagatha" },
  { name: "Dharmalingam Jeyanthan a.ka. Muhunthan" },
  { name: "Kumarasamy Dharmakumar a.k.a Puduwendran a.k.a Puwendran" },
  { name: "Jeyarathnam Rudrakumar a.k.a Rudra a.k.a Senduran" },
  { name: "Markandu Sivaruban" },
  { name: "Velliah Thayalan a.k.a Paramadewa" },
  { name: "Yesurasa Amaladas a.k.a Arun" },
  { name: "Manikkamawayagam Karthipan a.k.a Karthik" },
  { name: "Kanthalingam Premareji a.k.a KP Reji" },
  { name: "Balasubramaniam Sri Skandarajah" },
  { name: "Conneliyas Prabhakaran a.k.a Komolis Prabhakaran" },
  { name: "Eliyathamby Thiresakumaran" },
  { name: "Kandiah Kunjithapadam" },
  { name: "Kathirakesu Ganeshalingam a.k.a Kasinadan Ganeshalingam" },
  { name: "Krishnakutti Sukumaran a.k.a Udayan" },
  { name: "Kurukulasingham Thevarasa" },
  { name: "Sebamalai Joijinas" },
  { name: "Thurairasa Priyadarshani" },
  { name: "Velupillai Sivanadiyar" },
  { name: "Andrahennadige Chaminda Dharshana a.k.a Ice Manju a.k.a. Manju" },
  { name: "Kamlarooban a.k.a Navaz a.k.a Suresh a.k.a Kapil Master" },
  { name: "Sellanainar Ravichandran a.k.a Rajendran Moorthi a.k.a Devan a.k.a Thevan a.k.a Ananthan" },
  { name: "Vishvanathan Ruththirakumaran a.k.a Vishvanathan Rudrakumaran a.k.a Kumaran Vishvanathan a.k.a Rudra" },
  { name: "Appathurai Sendil Vinayagam a.k.a Sendil Vijayahana" },
  { name: "Arumugam Thayabaran a.k.a Thaya a.k.a Nimalan" },
  { name: "Chandra Varthakumar" },
  { name: "Weerabahu Nadarajah" },
  { name: "Punkulali Weeran a.k.a Malaysian Akka a.k.a Palaveeran Punkuli" },
  { name: "Perimbanayagam Sivaparan a.k.a Nediyawan a.k.a November India" },
  { name: "Weerasingham Nageshwaran a.k.a Puwanan Master" },
  { name: "Kandasamy Kamalaraj" },
  { name: "Nadaraja Sathyaseelan a.k.a Seel Maran" },
  { name: "Kamalasinham Arunakulasinham a.k.a Kamal" },
  { name: "Antonyrasa Caliston a.k.a Parathan" },
  { name: "Sivasubramaniyam Jeya Ganesh a.k.a Samraj a.k.a Ganesh" },
  { name: "Ponnasami Paskaran a.k.a Jeyakaran" },
  { name: "Suresh Kumar Pradeep" },
  { name: "Kanthasamy Krishnamoorthi a.k.a Moorthi" },
  { name: "Jeewarathnam Jeewakumar a.k.a Siranjeew Master" },
  { name: "Tony Jehan Murugesupillai a.k.a Ashok" },
  { name: "Gnanasundaram Suresh Kumar a.k.a Sera" },
  { name: "Karupaiya Tangawelu Maheshwaran a.k.a Anbu (Doctor)" },
  { name: "Thawarasa Udayadas a.k.a Udaya Sankar a.k.a Shankar" },
  { name: "Balasubamaniyam Sivaneshan a.k.a Iseypriyan a.k.a Piriyan a.k.a Anbu Neshan" },
  { name: "Welayudam Kandavanam Maheshwaram a.k.a Gobi" },
  { name: "Mahathmaji Anojan a.k.a Vettri a.k.a Kannan" },
  { name: "Amirthalingam Thilipan a.k.a Thilipan Master" },
  { name: "Sagadevan Wasanthakala" },
  { name: "Singharasa Vines a.k.a Punchikuli Vines" },
  { name: "Ramaiya Vivekandan a.k.a Periyavan a.k.a Kandan a.k.a Alex" },
  { name: "Nithyanandan Kajakokilan a.k.a Victor a.k.a Kajan" },
  { name: "Kanapathipille Kavinas a.k.a Nirmalan a.k.a Nirmalanadan a.k.a Nimalan" },
  { name: "Paramanadan Yadavan a.k.a Santhosham Master a.k.a Santhosham" },
  { name: "Vinayagamoorthi Mohanasundaram a.k.a Jenarthan a.k.a Vadivel Mohan" },
  { name: "Kamalanadan Sathis Kumar a.k.a Ambalavanar Sathis Kumar a.k.a Kumaran a.k.a Thuiyavan a.k.a Iniyavan a.k.a Inban a.k.a Mama" },
  { name: "Kandasami Krishnakumar a.k.a Kandan a.k.a Kaja a.k.a Kumar" },
  { name: "Suresh a.k.a Amudan a.k.a Seira a.k.a Muhundan a.k.a Maran Anna" },
  { name: "Pakyan Thirunawkarasu a.k.a Daya Mohan a.k.a Pakkiraraja" },
  { name: "Mohamadu Ibrahim Mohamadu Naufer a.k.a Abu Seid a.k.a Abu Sharim" },
  { name: "Muhammed Sawaheer Muhammed Hasan" },
  { name: "Umeir Mohammed Iqbal a.k.a Abu Afiya" },
  { name: "Mohammadu Akram Ahkam" },
  { name: "Muinadeen Ishan Ahmed" },
  { name: "Mohammed Ifthikar Mohammed Insaf" },
  { name: "Abdul Kadar Mohammed Shazni" },
  { name: "Mohammed Faruk Mohammed Hilam a.k.a Abu Haitam" },
  { name: "Huseinul Risvi Kalid Sameer" },
  { name: "Hayaththu Mohammadu Ahamed Milhan a.k.a Abu Shila" },
  { name: "Mohammed Ibbraheem Sahid Abdul Haq a.k.a Abu Falah" },
  { name: "Mohammed Ibbraheem Sadiq Abdullah a.k.a Abu Umar" },
  { name: "Mohammadu Sarifu Adam Lebbe a.k.a Mohammed Sarif Adam Lebbe a.k.a Gafur Mama a.k.a Abu Hadeed" },
  { name: "Mohammed Infas Inayathulla" },
  { name: "Abdul Latheef Mohammed Safi a.k.a Abu Furkahan" },
  { name: "Muhammadu Marsuk Muhammadu Rila a.k.a Abu Liba" },
  { name: "Mohideen Kani Sehu Munajithu a.k.a Munajith Maulavi a.k.a Muhadeenkani Sehu Munajithu" },
  { name: "Mohammed Suhair Mohammed Aroos a.k.a Abu Asia" },
  { name: "Mohammed Thawsi Thajudeen" },
  { name: "Mohammed Muhusin Ishak Ahamed" },
  { name: "Yusuf Mohamad Ibbraheem" },
  { name: "Abdul Kadar Fathima Hadiya a.k.a Siththiya" },
  { name: "Mohomed Ramees Mohomed Sajidh a.k.a Abu Najah" },
  { name: "Muhammadu Mansoor Mohammed Fairoos" },
  { name: "Mohammed Amees Mohammed Adil a.k.a Adil" },
  { name: "Mohammed Fawmi Fabnum Minasha" },
  { name: "Muhammadh Imad Ibithisami Fakeer a.k.a Imadh" },
  { name: "Mohammed Unais Mohammed Ameen" },
  { name: "Mohomad Bazeer Mohomad Fashan a.k.a Abu Seilani" },
  { name: "Mohomad Musthafa Mohomad Risvan" },
  { name: "Mohomad Anwar Mohomad Riskan a.k.a Abu Thariq" },
  { name: "Mohamad Mansoor Mohamad Sanasdeen a.k.a Abu Misan" },
  { name: "Abdul Manaf Mohomad Firdavus a.k.a Abu Kuthafa" },
  { name: "Hamsa Mohodeen Mohamadu Imran" },
  { name: "Abu Hanifa Mohammed Mufees a.k.a Abu Dahida" },
  { name: "Ameer Hamsa Mohammed Hamas a.k.a Abu Shafiya" },
  { name: "Raseed Mohammed Ibbraheem a.k.a Abu Abdul Rahuman" },
  { name: "Mohammed Safee Mohideen Abdul Kadar a.k.a Abu Suleiman" },
  { name: "Mohammed Hanifa Seinul Abdeen a.k.a Abu Hina" },
  { name: "Fasral Rahuman Mohammed Saharan a.k.a Abu Huddaifa" },
  { name: "Mohammed Musthafa Mohammed Haris a.k.a Abu Nanjihar" },
  { name: "Abdul Hameed Mohammed Rifas a.k.a Abu Abbas" },
  { name: "Mohammadu Abdul Kadar Mohammadu Ansar" },
  { name: "Fathima Seenath Akbar" },
  { name: "Thajul Judi Thajudeen" },
  { name: "Fathima Rawsi Thajudeen" },
  { name: "Suhaira Sinnathambi Uthumalebbe a.k.a Uthumalebbe Suhaira" },
  { name: "Seenathul Arafa Farook" },
  { name: "Mohamed Thajudeen Thaskeer Ahammed" },
  { name: "Vijayaratnam Sivanesan a.k.a Ragupathy a.k.a Sivan a.k.a Neshan a.k.a Ragu" },
  { name: "Selliah Jeyabalan a.k.a Abdulla a.k.a Selliah Polan" },
  { name: "Pasupathipillai Udayamoorthy a.k.a Pasupathi Udayamoorthy" },
  { name: "Poobalasingham Thirubalasingham a.k.a Rajan" },
  { name: "Sabapathi Wimalanathan" },
  { name: "Sellakkili Anandarasan a.k.a Daya" },
  { name: "Sinnarajah Ravisankar a.k.a Sankar" },
  { name: "Sinniah Mahesvaran" },
  { name: "Subramaniam Sundaralingam a.k.a Sundar" },
  { name: "Thamotharapillai Sivanathan a.k.a Siva" },
  { name: "Vairavanadan Nimalan" },
  { name: "Viramuttu Thavarasa" },
  { name: "Kanagasabai Parani Roobasingam" },
  { name: "Selvarajah Jeevarani" },
  { name: "Selliah Loganathan" },
  { name: "Punniyamoorthi Kirubakaran a.k.a Ilakkiyan Master" },
  { name: "Mari Chandrakumar a.k.a Siranjeew Master" },
  { name: "Maharuf Mohommed Ashiq a.k.a Bai Ashiq" },
  { name: "Sinniah Sivaruban a.k.a Thawan" },
  { name: "Joseph Peter Robinson a.k.a Theepan a.k.a Seelalan" },
  { name: "Selvarasa Uthayasivam a.k.a Udayan Master" },
  { name: "Thanam Pushpalakshmi a.k.a Kayal Latha a.k.a Latha Akka" },
  { name: "Meera Sahib Mohomed Nafali a.k.a Nafli Brother a.k.a Abu Sana" },
  { name: "Asanar Muhammadu Ramees a.k.a Pawas a.k.a Abu Aiman" },
  { name: "Aisha Siddika Mohomed Wasir" },
  { name: "Muhammadu Ismail Muhammadu Ilham" },
  { name: "Jeinul Abdeen Mohomadu Jeseem" },
  { name: "Mohomed Risvi Aflal Ahamed" },
  { name: "Mohideen Bawa Mohomed Roomi a.k.a Abu Abrar" },
  { name: "Muhammadu Sahir Muhammadu Ahsan" },
  { name: "Mohamed Rapaideen Mohamed Ali a.k.a Ali" },
  { name: "Seinul Abdin Hafsal a.k.a Abu Rawa" },
  { name: "Sahul Hameedu Muhammadu a.k.a Sawl Hameed Hamees Mohomed a.k.a Siyam" },
  { name: "Mihardin Muhammad Suhri" },
  { name: "Kichchi Muhammed Muhammadu Jemisan" },
  { name: "Abdul Haq Mohommed Sameer" },
  { name: "Mohommadu Abdul Kadar Mohommadu Aseem a.k.a Abu Ammar" },
  { name: "Mohommed Nisam Mohommed Wasim a.k.a Abu Masud" },
  { name: "Hasbulla Shan Hamthi Ahammed a.k.a Abu Sahal" },
  { name: "Mokana Suntharam Sinnaththurai a.k.a Mohana Sundaram Sinnaththurai a.k.a Ragu" },
  { name: "Edirimanasinham Pirabu" },
  { name: "Mahendran Partheeban a.k.a Theeban a.k.a Anbu a.k.a Anbumaran" },
  { name: "Sabarathnam Thuiwan" },
  { name: "Ramesh Suyanthan" },
  { name: "Anton Charls Pavithran" },
  { name: "Kunalingam Vasanthan" },
  { name: "Manoharan Kumaraswami" },
  { name: "Raththina Palasingham Ilavethan a.k.a Ilau" },
  { name: "Udayasorooban Umasudan a.k.a Uma" },
  { name: "Lingeshvaran Imbaraja a.k.a Imban" },
  { name: "Selvapakayam Suthakaran a.k.a Navalan" },
  { name: "Kirupairaja Sathyarooban a.k.a Pormaran" },
  { name: "Pakyathurei Naguleswaran a.k.a Nagulan a.k.a Arasu" },
  { name: "Thangaraja Jeyanthan a.k.a Jeram" },
  { name: "Thangathure Nishanthan a.k.a Sudar a.k.a Suman" },
  { name: "Kanagalingam Wijayadojini a.k.a Wijitha" },
  { name: "Abdul Kadar Mohamed Ajmir a.k.a Abu Dujana" },
  { name: "Mohammadu Mashudh Muhammadu Rikas" },
  { name: "Sinnathambi Kanagalingam a.k.a Maniarasan" },
  { name: "Rasik Rasa Husain" },
  { name: "Abdul Samathu Mohomadu Safan" },
  { name: "Muhammadu Rahamathulla Fathima Jusna" },
  { name: "Mohomed Munas Muwadh" },
  { name: "Najimudeen Mohomed Fawshan" },
  { name: "Mohomed Faleel Fathima Shahida" },
  { name: "Mohomed Shasim Madaniya" },
  { name: "Adam Lebbe Muhammadu Irfan" },
  { name: "Hinuru Mohomadeen Mohomadu Aseem" },
  { name: "Muhammadu Husain Abdul Kadar" },
  { name: "Mohomed Ibrahim Saeeda" },
  { name: "Ahamed Thalib Luqman Thalib" },
  { name: "Ahamed Luqman Thalib" },
  { name: "Rasaiya Anandarasa a.k.a Logesh a.k.a Sinnawan" },
  { name: "Selvanayagam Devanayagam a.k.a Devan a.k.a Kugan" },
  { name: "Kumarasami Baskaran a.k.a Mayuran" },
  { name: "Kaidponkalan Antoni Dunstan a.k.a Balendi a.k.a Pandithar a.k.a Siva" },
  { name: "Velupille Nadarasa Jegadeeswaran a.k.a Samar" },
  { name: "Uwais Seifur Rahman a.k.a Abu-Baqdadi" },
  { name: "Sambasivan Sajithan a.k.a Saji" },
  { name: "Mohomed Haris Nisar Mohomed Irshad" },
  { name: "Mohammadu Nilabdeen Mohammadu Rimsan a.k.a Abdur a.k.a Abdurrahman" },
  { name: "Ahamed Hisham a.k.a Mentei a.k.a Baba" },
  { name: "Mohamed Ismail a.k.a Isei a.k.a Sim" },
  { name: "Mohomed Nishan a.k.a Mohaddei a.ka Tru a.k.a Mode" },
  { name: "Ismail Thaufik Mohomad a.k.a Isei" },
  { name: "Safaf Mohamed" },
];
